/**
 * Efeitos de isca do Cobblemon 1.8.2 (data/cobblemon/spawn_bait_effects/**, 79 arquivos), portados à mão
 * para o formato do port. Chave = identificador do registro (SpawnBaitEffects), `item` = item que é a isca.
 * Campos: type (sem namespace), sub (subcategory sem namespace), chance (0–1), value.
 */
import type { BaitEffect } from "./BaitEffects";

export interface BaitDefinition {
  item: string;
  effects: BaitEffect[];
}

export const SPAWN_BAITS: Record<string, BaitDefinition> = {
  "cobblemon:berries/aguav_berry": { item: "cobblemon:aguav_berry", effects: [{ type: "nature", sub: "spd", chance: 0.5 }] },
  "cobblemon:berries/apicot_berry": { item: "cobblemon:apicot_berry", effects: [{ type: "iv", sub: "spd", chance: 1.0, value: 5.0 }] },
  "cobblemon:berries/aspear_berry": { item: "cobblemon:aspear_berry", effects: [{ type: "egg_group", sub: "water_1", chance: 1.0, value: 10.0 }, { type: "egg_group", sub: "water_2", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/babiri_berry": { item: "cobblemon:babiri_berry", effects: [{ type: "typing", sub: "steel", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/belue_berry": { item: "cobblemon:belue_berry", effects: [{ type: "nature", sub: "def", chance: 1.0 }] },
  "cobblemon:berries/bluk_berry": { item: "cobblemon:bluk_berry", effects: [{ type: "nature", sub: "spa", chance: 0.25 }] },
  "cobblemon:berries/charti_berry": { item: "cobblemon:charti_berry", effects: [{ type: "typing", sub: "rock", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/cheri_berry": { item: "cobblemon:cheri_berry", effects: [{ type: "egg_group", sub: "fairy", chance: 1.0, value: 10.0 }, { type: "egg_group", sub: "grass", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/chesto_berry": { item: "cobblemon:chesto_berry", effects: [{ type: "egg_group", sub: "human_like", chance: 1.0, value: 10.0 }, { type: "egg_group", sub: "flying", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/chilan_berry": { item: "cobblemon:chilan_berry", effects: [{ type: "typing", sub: "normal", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/chople_berry": { item: "cobblemon:chople_berry", effects: [{ type: "typing", sub: "fighting", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/coba_berry": { item: "cobblemon:coba_berry", effects: [{ type: "typing", sub: "flying", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/colbur_berry": { item: "cobblemon:colbur_berry", effects: [{ type: "typing", sub: "dark", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/cornn_berry": { item: "cobblemon:cornn_berry", effects: [{ type: "nature", sub: "spa", chance: 0.75 }] },
  "cobblemon:berries/custap_berry": { item: "cobblemon:custap_berry", effects: [{ type: "drops_reroll", chance: 1.0, value: 1.0 }] },
  "cobblemon:berries/durin_berry": { item: "cobblemon:durin_berry", effects: [{ type: "nature", sub: "spd", chance: 1.0 }] },
  "cobblemon:berries/eggant_berry": { item: "cobblemon:eggant_berry", effects: [{ type: "egg_group", sub: "ditto", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/enigma_berry": { item: "cobblemon:enigma_berry", effects: [{ type: "ha_chance", chance: 0.05 }] },
  "cobblemon:berries/figy_berry": { item: "cobblemon:figy_berry", effects: [{ type: "nature", sub: "atk", chance: 0.5 }] },
  "cobblemon:berries/ganlon_berry": { item: "cobblemon:ganlon_berry", effects: [{ type: "iv", sub: "def", chance: 1.0, value: 5.0 }] },
  "cobblemon:berries/glow_berries": { item: "minecraft:glow_berries", effects: [{ type: "bite_time", chance: 1.0, value: 0.33 }] },
  "cobblemon:berries/grepa_berry": { item: "cobblemon:grepa_berry", effects: [{ type: "ev", sub: "spd", chance: 1.0, value: 100.0 }] },
  "cobblemon:berries/haban_berry": { item: "cobblemon:haban_berry", effects: [{ type: "typing", sub: "dragon", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/hondew_berry": { item: "cobblemon:hondew_berry", effects: [{ type: "ev", sub: "spa", chance: 1.0, value: 100.0 }] },
  "cobblemon:berries/hopo_berry": { item: "cobblemon:hopo_berry", effects: [{ type: "alpha_chance", chance: 0.02 }] },
  "cobblemon:berries/iapapa_berry": { item: "cobblemon:iapapa_berry", effects: [{ type: "nature", sub: "def", chance: 0.5 }] },
  "cobblemon:berries/jaboca_berry": { item: "cobblemon:jaboca_berry", effects: [{ type: "size", chance: 1.0, value: 50.0 }] },
  "cobblemon:berries/kasib_berry": { item: "cobblemon:kasib_berry", effects: [{ type: "typing", sub: "ghost", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/kebia_berry": { item: "cobblemon:kebia_berry", effects: [{ type: "typing", sub: "poison", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/kee_berry": { item: "cobblemon:kee_berry", effects: [{ type: "gender_chance", sub: "female", chance: 0.25 }] },
  "cobblemon:berries/kelpsy_berry": { item: "cobblemon:kelpsy_berry", effects: [{ type: "ev", sub: "atk", chance: 1.0, value: 100.0 }] },
  "cobblemon:berries/lansat_berry": { item: "cobblemon:lansat_berry", effects: [{ type: "iv", sub: "hp", chance: 1.0, value: 5.0 }] },
  "cobblemon:berries/leppa_berry": { item: "cobblemon:leppa_berry", effects: [{ type: "level_raise", chance: 1.0, value: 5.0 }] },
  "cobblemon:berries/liechi_berry": { item: "cobblemon:liechi_berry", effects: [{ type: "iv", sub: "atk", chance: 1.0, value: 5.0 }] },
  "cobblemon:berries/lum_berry": { item: "cobblemon:lum_berry", effects: [{ type: "egg_group", sub: "dragon", chance: 1.0, value: 10.0 }, { type: "egg_group", sub: "monster", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/mago_berry": { item: "cobblemon:mago_berry", effects: [{ type: "nature", sub: "spe", chance: 0.5 }] },
  "cobblemon:berries/magost_berry": { item: "cobblemon:magost_berry", effects: [{ type: "nature", sub: "spe", chance: 0.75 }] },
  "cobblemon:berries/maranga_berry": { item: "cobblemon:maranga_berry", effects: [{ type: "gender_chance", sub: "male", chance: 0.25 }] },
  "cobblemon:berries/micle_berry": { item: "cobblemon:micle_berry", effects: [{ type: "mark_chance", chance: 1.0, value: 5.0 }] },
  "cobblemon:berries/nanab_berry": { item: "cobblemon:nanab_berry", effects: [{ type: "nature", sub: "spe", chance: 0.25 }] },
  "cobblemon:berries/nomel_berry": { item: "cobblemon:nomel_berry", effects: [{ type: "nature", sub: "def", chance: 0.75 }] },
  "cobblemon:berries/occa_berry": { item: "cobblemon:occa_berry", effects: [{ type: "typing", sub: "fire", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/oran_berry": { item: "cobblemon:oran_berry", effects: [{ type: "bite_time", chance: 1.0, value: 0.33 }] },
  "cobblemon:berries/pamtre_berry": { item: "cobblemon:pamtre_berry", effects: [{ type: "nature", sub: "spa", chance: 1.0 }] },
  "cobblemon:berries/passho_berry": { item: "cobblemon:passho_berry", effects: [{ type: "typing", sub: "water", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/payapa_berry": { item: "cobblemon:payapa_berry", effects: [{ type: "typing", sub: "psychic", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/pecha_berry": { item: "cobblemon:pecha_berry", effects: [{ type: "egg_group", sub: "water_3", chance: 1.0, value: 10.0 }, { type: "egg_group", sub: "bug", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/persim_berry": { item: "cobblemon:persim_berry", effects: [{ type: "egg_group", sub: "mineral", chance: 1.0, value: 10.0 }, { type: "egg_group", sub: "amorphous", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/petaya_berry": { item: "cobblemon:petaya_berry", effects: [{ type: "iv", sub: "spa", chance: 1.0, value: 5.0 }] },
  "cobblemon:berries/pinap_berry": { item: "cobblemon:pinap_berry", effects: [{ type: "nature", sub: "def", chance: 0.25 }] },
  "cobblemon:berries/pomeg_berry": { item: "cobblemon:pomeg_berry", effects: [{ type: "ev", sub: "hp", chance: 1.0, value: 100.0 }] },
  "cobblemon:berries/qualot_berry": { item: "cobblemon:qualot_berry", effects: [{ type: "ev", sub: "def", chance: 1.0, value: 100.0 }] },
  "cobblemon:berries/rabuta_berry": { item: "cobblemon:rabuta_berry", effects: [{ type: "nature", sub: "spd", chance: 0.75 }] },
  "cobblemon:berries/rawst_berry": { item: "cobblemon:rawst_berry", effects: [{ type: "egg_group", sub: "field", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/razz_berry": { item: "cobblemon:razz_berry", effects: [{ type: "nature", sub: "atk", chance: 0.25 }] },
  "cobblemon:berries/rindo_berry": { item: "cobblemon:rindo_berry", effects: [{ type: "typing", sub: "grass", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/roseli_berry": { item: "cobblemon:roseli_berry", effects: [{ type: "typing", sub: "fairy", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/rowap_berry": { item: "cobblemon:rowap_berry", effects: [{ type: "size", chance: 1.0, value: -50.0 }] },
  "cobblemon:berries/salac_berry": { item: "cobblemon:salac_berry", effects: [{ type: "iv", sub: "spe", chance: 1.0, value: 5.0 }] },
  "cobblemon:berries/shuca_berry": { item: "cobblemon:shuca_berry", effects: [{ type: "typing", sub: "ground", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/sitrus_berry": { item: "cobblemon:sitrus_berry", effects: [{ type: "bite_time", chance: 1.0, value: 0.5 }] },
  "cobblemon:berries/spelon_berry": { item: "cobblemon:spelon_berry", effects: [{ type: "nature", sub: "atk", chance: 1.0 }] },
  "cobblemon:berries/starf_berry": { item: "cobblemon:starf_berry", effects: [{ type: "shiny_reroll", chance: 1.0, value: 4.0 }] },
  "cobblemon:berries/sweet_berries": { item: "minecraft:sweet_berries", effects: [{ type: "bite_time", chance: 1.0, value: 0.25 }] },
  "cobblemon:berries/tamato_berry": { item: "cobblemon:tamato_berry", effects: [{ type: "ev", sub: "spe", chance: 1.0, value: 100.0 }] },
  "cobblemon:berries/tanga_berry": { item: "cobblemon:tanga_berry", effects: [{ type: "typing", sub: "bug", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/touga_berry": { item: "cobblemon:touga_berry", effects: [{ type: "nature", sub: "atk", chance: 0.75 }] },
  "cobblemon:berries/wacan_berry": { item: "cobblemon:wacan_berry", effects: [{ type: "typing", sub: "electric", chance: 1.0, value: 10.0 }] },
  "cobblemon:berries/watmel_berry": { item: "cobblemon:watmel_berry", effects: [{ type: "nature", sub: "spe", chance: 1.0 }] },
  "cobblemon:berries/wepear_berry": { item: "cobblemon:wepear_berry", effects: [{ type: "nature", sub: "spd", chance: 0.25 }] },
  "cobblemon:berries/wiki_berry": { item: "cobblemon:wiki_berry", effects: [{ type: "nature", sub: "spa", chance: 0.5 }] },
  "cobblemon:berries/yache_berry": { item: "cobblemon:yache_berry", effects: [{ type: "typing", sub: "ice", chance: 1.0, value: 10.0 }] },
  "cobblemon:fruits/apple": { item: "minecraft:apple", effects: [{ type: "bite_time", chance: 1.0, value: 0.5 }] },
  "cobblemon:fruits/enchanted_golden_apple": { item: "minecraft:enchanted_golden_apple", effects: [{ type: "bite_time", chance: 1.0, value: 1.0 }, { type: "rarity_bucket", chance: 1.0, value: 10 }, { type: "shiny_reroll", chance: 1.0, value: 9.0 }] },
  "cobblemon:fruits/glistering_melon_slice": { item: "minecraft:glistering_melon_slice", effects: [{ type: "rarity_bucket", chance: 1.0, value: 1 }] },
  "cobblemon:fruits/golden_apple": { item: "minecraft:golden_apple", effects: [{ type: "bite_time", chance: 1.0, value: 0.75 }, { type: "rarity_bucket", chance: 1.0, value: 1 }, { type: "shiny_reroll", chance: 1.0, value: 1.0 }] },
  "cobblemon:fruits/golden_carrot": { item: "minecraft:golden_carrot", effects: [{ type: "rarity_bucket", chance: 1.0, value: 1 }] },
  "cobblemon:poke_bait": { item: "cobblemon:poke_bait", effects: [] },
  "cobblemon:sweet_heart": { item: "cobblemon:sweet_heart", effects: [{ type: "friendship", chance: 1.0, value: 35.0 }] },
};
